# Generated by Django 4.1.3 on 2023-08-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('etag', models.CharField(max_length=50)),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('published_at', models.DateTimeField()),
                ('channel_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_thumbnail_url', models.URLField()),
                ('medium_thumbnail_url', models.URLField()),
                ('high_thumbnail_url', models.URLField()),
                ('channel_title', models.CharField(max_length=100)),
                ('live_broadcast_content', models.CharField(max_length=20)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
    ]
